Backend Projects/CateringSite/djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users.views import MyPasswordResetView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("catering.urls")),
    path("contact/", include("contact.urls")),
    path("register/", user_views.RegisterView.as_view(), name="register"),
    path('login/', auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path('logout/', user_views.MyLogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL},
         name="logout"),

    path('password-reset/',
        MyPasswordResetView.as_view(template_name="users/password_reset.html"),
         name="password_reset"),

    path('password-reset-confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html"),
         name="password_reset_confirm"),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name="password_reset_complete"),

    path('password-reset/done',
         auth_views.PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name="password_reset_done"),

    path("offer/", include("menu.urls")),
    path("cart/", include("checkout.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Backend Projects/CateringSite/menu/urls.py
from django.urls import path
from menu.views import MenuDetailView, MenuListView

urlpatterns = [
    path('', MenuListView.as_view(), name="offer"),
    path("<slug:dietname>/", MenuDetailView.as_view(), name="offer_detail"),

]

Backend Projects/CateringSite/menu/models.py
from PIL import Image
from django.db import models
from django.utils.text import slugify


class Diet(models.Model):
    name = models.CharField(max_length=30)
    image = models.ImageField(upload_to='diet_images')
    description = models.TextField()
    price = models.FloatField(default=0)
    slug = models.SlugField()

    def __str__(self) -> str:
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

        super().save(*args, **kwargs)



class DietExample(models.Model):
    first_dish = models.TextField()
    second_dish = models.TextField()
    third_dish = models.TextField()
    fourth_dish = models.TextField()
    fifth_dish = models.TextField()
    diet = models.ForeignKey(Diet, on_delete=models.PROTECT)

    def __str__(self) -> str:
        return f"{self.diet} Example"

Backend Projects/CateringSite/menu/views.py
from django.views.generic import DetailView, ListView
from menu.models import Diet, DietExample


class MenuListView(ListView):
    model = Diet
    template_name = "menu/offer.html"
    context_object_name = "diets"


class MenuDetailView(DetailView):
    model = Diet
    context_object_name = "diet"
    template_name = "menu/offer_details.html"
    slug_url_kwarg = 'dietname'
    slug_field = 'slug'


class DietExampleDetail(DetailView):
    model = DietExample
    context_object_name = "dietexample"
    template_name = "menu/example_diet_table.html"

Backend Projects/CateringSite/menu/templates/menu/example_diet_table.html
<table class="table">
    <thead class="thead-dark">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Number of the meal</th>
        <th scope="col">Meal</th>

    </tr>
    </thead>
    <tbody>
    <tr>
        <th scope="row">1</th>
        <td>{{ meals.first_dish }}</td>

    </tr>
    <tr>
        <th scope="row">2</th>
        <td>{{ meals.second_dish }}</td>

    </tr>
    <tr>
        <th scope="row">3</th>
        <td>{{ meals.third_dish }}</td>

    </tr>
    <tr>
        <th scope="row">4</th>
        <td>{{ meals.fourth_dish }}</td>

    </tr>
    <tr>
        <th scope="row">5</th>
        <td>{{ meals.fifth_dish }}</td>

    </tr>

    </tbody>
</table>

Backend Projects/CateringSite/menu/templates/menu/offer.html
{% extends  "catering/base.html" %}
{% block content %}
    {% block head %}
    <title> Offer </title>
{% endblock %}
    {% for diet in diets %}
        <article class="media content-section">
            <img class="rounded-circle" src="{{ diet.image.url }} " width="300px" height="300px">
            <div class="media-body">

                <h2><a class="article-title" href="{% url "offer_detail" diet.slug %}">{{ diet.name }}</a></h2>
                <p class="article-content">{{ diet.description }}</p>
            </div>
        </article>
    {% endfor %}
{% endblock %}

Backend Projects/CateringSite/menu/templates/menu/offer_details.html
{% extends  "catering/base.html" %}
{% block content %}
{% block head %}
    <title>{{ diet.name }}</title>
{% endblock %}
    <article class="media content-section">
        <img class="rounded-circle" src="{{ diet.image.url }}" width="300px" height="300px" >
        <div class="media-body">
            <h2><a class="article-title">{{ diet.name }}</a></h2>
            <p class="article-content">{{ diet.description }}</p>
            <p class="price">{{ diet.price }} PLN per day</p>
        </div>
    </article>


    <h2>Example Menu</h2>
    {% for meals in diet.dietexample_set.all %}

        {% include 'menu/example_diet_table.html' %}

    {% endfor %}

    <form action={% url "add_product" %}>
        <input type="submit" value="Make an Order!"/>
    </form>

{% endblock %}