Backend Projects/CateringSite/checkout/urls.py
from django.urls import path
from .views import CartView, DietOrderView, OrderUpdateView, OrderDeleteView, CheckoutView, MyOrdersHistory, \
    MyOrdersHistoryDetail

urlpatterns = [
    path("", CartView.as_view(), name="cart"),
    path('add-product/', DietOrderView.as_view(), name="add_product"),
    path("orders_history/", MyOrdersHistory.as_view(), name="orders_history"),
    path("orders_history/<str:user>/<int:pk>", MyOrdersHistoryDetail.as_view(), name="orders_history_detail"),
    path('update/<str:user>/<int:pk>/', OrderUpdateView.as_view(), name="order_update"),
    path('delete/<str:user>/<int:pk>/', OrderDeleteView.as_view(), name="order_delete"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),




]

Backend Projects/CateringSite/djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users.views import MyPasswordResetView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("catering.urls")),
    path("contact/", include("contact.urls")),
    path("register/", user_views.RegisterView.as_view(), name="register"),
    path('login/', auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path('logout/', user_views.MyLogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL},
         name="logout"),

    path('password-reset/',
        MyPasswordResetView.as_view(template_name="users/password_reset.html"),
         name="password_reset"),

    path('password-reset-confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html"),
         name="password_reset_confirm"),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name="password_reset_complete"),

    path('password-reset/done',
         auth_views.PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name="password_reset_done"),

    path("offer/", include("menu.urls")),
    path("cart/", include("checkout.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Backend Projects/CateringSite/menu/urls.py
from django.urls import path
from menu.views import MenuDetailView, MenuListView

urlpatterns = [
    path('', MenuListView.as_view(), name="offer"),
    path("<slug:dietname>/", MenuDetailView.as_view(), name="offer_detail"),

]

Backend Projects/CateringSite/checkout/models.py
import datetime
from django.db import models
from django.urls import reverse
from django.utils import timezone

from djangoProject.settings import HOLIDAYS_POLAND
from menu.models import Diet
from users.models import Customer


class OrderCheckout(models.Model):
    email = models.EmailField()
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT)
    date_of_purchase = models.DateTimeField(default=timezone.now)
    payment_method = models.TextField()
    to_pay = models.FloatField(null=True)
    surname = models.CharField(max_length=15)
    name = models.CharField(max_length=20)
    telephone = models.CharField(max_length=15)
    address = models.CharField(max_length=100)
    address_info = models.CharField(max_length=50)
    locality = models.CharField(max_length=25)
    state = models.CharField(max_length=25)
    post_code = models.CharField(max_length=6)
    note = models.TextField()

    def __str__(self) -> str:
        return f"{self.email} {self.customer} {self.date_of_purchase}, {self.payment_method}"

    def get_absolute_url(self) -> str:
        return reverse("order_history", kwargs={"user": self.customer, "pk": self.pk, })


class DietOrder(models.Model):
    name = models.ForeignKey(Diet, on_delete=models.PROTECT)
    megabytes = models.IntegerField()
    days = models.IntegerField()
    to_pay = models.FloatField()
    delivery_cost = models.FloatField()
    diet_cost = models.FloatField()
    delivery_cost_per_day = models.FloatField()
    diet_cost_per_day = models.FloatField()
    date_of_start = models.DateField()
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT)
    date_of_end = models.DateField()
    address = models.CharField(max_length=100)
    address_info = models.CharField(max_length=50)
    locality = models.CharField(max_length=25)
    state = models.CharField(max_length=25)
    post_code = models.CharField(max_length=8)
    distance = models.FloatField()
    is_purchased = models.BooleanField(default=False)
    is_up_to_date = models.BooleanField(default=True)
    confirmed_order = models.ForeignKey(OrderCheckout, on_delete=models.CASCADE, null=True)

    def calculate_whole_price(self) -> None:
        self.to_pay = self.diet_cost + self.delivery_cost

    def calculate_diet_cost(self) -> None:
        self.diet_cost = self.days * self.diet_cost_per_day

    def calculate_delivery_cost(self) -> None:
        self.delivery_cost = self.delivery_cost_per_day * self.days

    def calculate_holidays_days_between_dates(self) -> int:
        dates_list = [self.date_of_start + datetime.timedelta(days=x) for x in
                      range(0, (self.date_of_end - self.date_of_start).days)]

        days_to_avoid = 0
        for day in dates_list:
            if day in HOLIDAYS_POLAND:
                days_to_avoid += 1

        return days_to_avoid

    def calculate_weekend_days(self) -> int:
        dates_list = [self.date_of_start + datetime.timedelta(days=x) for x in
                      range(0, (self.date_of_end - self.date_of_start).days)]
        days_to_avoid = 0
        for date in dates_list:
            if date.weekday() in range(5, 7) and date.weekday() not in HOLIDAYS_POLAND:
                days_to_avoid += 1

        return days_to_avoid

    def calculate_days_between_dates(self, holidays_days, weekend_days) -> None:
        """ days + 1 because, catering includes last day, not only difference between days"""
        days = (self.date_of_end - self.date_of_start).days - holidays_days - weekend_days
        self.days = days + 1

    def calculate_extra_costs_for_delivery_per_day(self) -> None:
        if 10 > self.distance > 5:
            self.delivery_cost_per_day = 5
        else:
            self.delivery_cost_per_day = 0

    def check_if_order_is_up_to_date(self) -> None:
        if self.date_of_start - timezone.now().date() <= datetime.timedelta(days=3):

            self.is_up_to_date = False


    def get_absolute_url(self) -> str:
        return reverse("cart", kwargs={"pk": self.pk, "user": self.customer})

    def __str__(self) -> str:
        return f"STARTS: {self.date_of_start} ENDS: {self.date_of_end}, {self.address}, {self.address_info}"


class RegistrationPrzelewy24(models.Model):
    merchantID = models.IntegerField(default=11111)
    posID = models.IntegerField(default=11111)
    sessionId = models.CharField(max_length=100, default="test7")
    amount = models.IntegerField(default=1)
    currency = models.CharField(max_length=3, default="PLN")
    description = models.CharField(max_length=1024, default="test order")
    email = models.EmailField(max_length=50, default="john.doe@example.com")
    client = models.CharField(max_length=40, null=True)
    address = models.CharField(max_length=80, null=True)
    zip = models.CharField(max_length=10, null=True)
    city = models.CharField(max_length=50, null=True)
    country = models.CharField(max_length=2, default="PL")
    phone = models.CharField(max_length=12, null=True)
    language = models.CharField(max_length=2, default="pl")
    method = models.IntegerField(null=True)
    urlReturn = models.URLField(default="http://127.0.0.1:8000/cart")
    urlStatus = models.CharField(max_length=250),
    timeLimit = models.IntegerField(default=5, null=True)
    channel = models.IntegerField(default=16, null=True)
    waitForResult = models.BooleanField(null=True)
    regulationAccept = models.BooleanField(default=False)
    shipping = models.IntegerField(models.IntegerField, null=True)
    transferLabel = models.CharField(max_length=20, null=True)
    mobileLib = models.IntegerField(default=1, null=True)
    sdkVersion = models.CharField(max_length=10, null=True)
    sign = models.CharField(max_length=100, default="596af9bc39271b4cfdab45937")
    encoding = models.CharField(max_length=15, null=True)
    methodRefId = models.CharField(max_length=250)

Backend Projects/CateringSite/checkout/forms.py
import datetime
from django import forms
from django.contrib.auth.models import User
from django.utils import timezone
from checkout.models import DietOrder, OrderCheckout
import re
from djangoProject.settings import POLISH_POST_CODE_REGEX, HOLIDAYS_POLAND


class NotLoggedUserOrderCheckoutForm(forms.ModelForm):
    PAYMENT_CHOICE = (
        ("Przelewy24", "Przelewy24"),
        ("Transfer", "Transfer"),
    )
    payment_method = forms.ChoiceField(choices=PAYMENT_CHOICE)
    telephone = forms.NumberInput()
    email = forms.EmailField()

    def clean(self) -> dict:
        super().clean()
        post_code = self.cleaned_data.get("post_code")
        email = self.cleaned_data.get("email")
        if not re.match(POLISH_POST_CODE_REGEX, post_code):
            self._errors["post_code"] = self.error_class(["Invalid postcode format"])

        user = User.objects.filter(email=email)
        if user:
            self._errors["email"] = self.error_class(["There is logged user with this email, please log in"])

        return self.cleaned_data

    class Meta:
        model = OrderCheckout

        fields = ["email", "surname", "name", "telephone", "address", "address_info", "locality", "state", "post_code",
                  "payment_method", "note"]


class LoggedUserOrderCheckoutForm(forms.ModelForm):
    PAYMENT_CHOICE = (
        ("Przelewy24", "Przelewy24"),
        ("Transfer", "Transfer"),
    )
    payment_method = forms.ChoiceField(choices=PAYMENT_CHOICE)
    telephone = forms.NumberInput()

    def clean(self) -> dict:
        super().clean()
        post_code = self.cleaned_data.get("post_code")
        if not re.match(POLISH_POST_CODE_REGEX, post_code):
            self._errors["post_code"] = self.error_class(["Invalid postcode format"])
        return self.cleaned_data

    class Meta:
        model = OrderCheckout

        fields = ["surname", "name", "telephone", "address", "address_info", "locality", "state", "post_code",
                  "payment_method", "note"]


class DateInput(forms.DateInput):
    input_type = 'date'


class DietOrderForm(forms.ModelForm):
    MEGABYTES_CHOICE = (
        ("1000", 1000),
        ("1500", 1500),
        ("2000", 2000),
        ("2500", 2500),
        ("3000", 3000),
        ("3500", 3500),
    )

    megabytes = forms.ChoiceField(choices=MEGABYTES_CHOICE)
    def validate_dates(self):

        date_of_start = self.cleaned_data.get("date_of_start")
        date_of_end = self.cleaned_data.get("date_of_end")
        if date_of_start < timezone.now().date() or date_of_start - timezone.now().date() <= datetime.timedelta(days=3):
            self._errors['date_of_start'] = self.error_class([
                'Date cannot be from past!\n'
                'Date must starts in 3 days ahead!'])

        if date_of_start in HOLIDAYS_POLAND or date_of_start.weekday() in range(5, 7):

            while date_of_start in HOLIDAYS_POLAND or date_of_start.weekday() in range(5, 7):
                date_of_start = date_of_start + datetime.timedelta(days=1)

            self._errors['date_of_start'] = self.error_class([
                f"It's holiday day or weekend, the closest termin is {date_of_start} "])

        if date_of_end in HOLIDAYS_POLAND or date_of_start.weekday() in range(5, 7):
            while date_of_end in HOLIDAYS_POLAND or date_of_start.weekday() in range(5, 7):
                date_of_end = date_of_end + datetime.timedelta(days=1)

            self._errors['date_of_end'] = self.error_class([
                f"It's holiday day, the closest termin is {date_of_end} "])

        if date_of_end < date_of_start:
            self._errors["date_of_end"] = self.error_class(["End of diet cannot be earlier than start"])



    def validate_post_code(self):
        post_code = self.cleaned_data.get("post_code")
        if not re.match(POLISH_POST_CODE_REGEX, post_code):
            self._errors["post_code"] = self.error_class(["Invalid postcode format"])

    def clean(self) -> dict:
        super().clean()
        self.validate_dates()
        self.validate_post_code()
        return self.cleaned_data

    class Meta:
        model = DietOrder

        fields = ["name", "megabytes", "date_of_start", "date_of_end", "address", "address_info", "locality", "state",
                  "post_code"]
        widgets = {
            'date_of_start': DateInput(),
            'date_of_end': DateInput(),
        }

Backend Projects/CateringSite/checkout/templates/checkout/api_view.html
{% extends "catering/base.html" %}
{% block head %}
    <title>{{ title }}</title>
{% endblock %}
{% block content %}
<div class="media-body">
                <h2 class="article-title"> This is simulated request </h2>
                <p class="article-content"> {{ request }}}</p>
</div>


<div class="media-body">
                <h2 class="article-title"> This is response</h2>
                <p class="article-content"> {{ response }}</p>
</div>


{% endblock %}

Backend Projects/CateringSite/checkout/templates/checkout/cart.html
{% extends "catering/base.html" %}
{% block content %}
{% block head %}
    <title>{{ title}}</title>
{% endblock %}
    {% for order in orders %}
        <article class="media content-section">
            <img class="rounded-circle" src="{{ order.name.image.url }}" alt="" width="300px" height="300px">
            <div class="media-body">
                <h2><a class="article-title">{{ order.name }}</a></h2>
                <p class="article-content">First delivery {{ order.date_of_start|date:"F d, Y" }}</p>
                <p class="article-content">Diet for {{ order.days }} day/s</p>
                <p class="article-content">Price per day {{ order.diet_cost_per_day }} PLN</p>
                <p class="article-content">Last delivery {{ order.date_of_end|date:"F d, Y" }}</p>
                <p class="article-content">Megabytes: {{ order.megabytes }}</p>
                <p class="article-content">Delivery costs: {{ order.delivery_cost }}</p>
                <p class="price">Price {{ order.to_pay }} PLN </p>
                <h2>DELIVERY</h2>
                <p class="price"> Main address: {{ order.address }} </p>
                <p class="price"> House number: {{ order.address_info }} </p>
                <p class="price"> {{ order.post_code }} {{ order.locality }} </p>

                {% if not order.is_up_to_date %}
                    <p class="text-danger">THIS ORDER IS NOT UP TO DATE, PLEASE CHANGE IT OR DELETE</p>
                {% endif %}


            </div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1"
               href="{% url "order_update" order.customer order.id %}  ">Change </a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url "order_delete" order.customer order.id %}">Delete </a>
        </article>
    {% endfor %}


    {% if orders %}
        <h4>Total Price {{ to_pay.to_pay__sum }} PLN</h4>
    {% else %}
        <h4>Your cart is empty :( </h4>
    {% endif %}


    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url "add_product" %}  ">Add Diet </a>

    <a class="btn btn-outline-dark btn-sm mt-1 mb-1" href="{% url "checkout" %}"> To Checkout </a>

{% endblock %}

Backend Projects/CateringSite/checkout/templates/checkout/checkout.html
{% extends "catering/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block head %}
    <title>{{ title}}</title>
{% endblock %}
{% block content %}
    <form method="POST">
        {% csrf_token %}

        {{ form|crispy }}

        <div class="form-group">
            <button class="btn-outline-info" type="submit">Purchase</button>

        </div>
        <div>
            <img class="img-thumbnail" src="{% static  "/checkout/images/transfer.png" %}">
        </div>
    </form>
{% endblock %}

Backend Projects/CateringSite/checkout/templates/checkout/detailed_orders_history.html
{% extends "catering/base.html" %}

{% block head %}
    <title>Order from {{ checkout.date_of_purchase }}</title>
{% endblock %}


{% block content %}



    {% for order in checkout.dietorder_set.all %}

        <article class="media content-section">
            <img class= "rounded-circle" src="{{ order.name.image.url }}" width="300px" height="300px">
            <div class="media-body">
                <h2><a class="article-title">{{ order.name }}</a></h2>
                <p class="article-content">First delivery {{ order.date_of_start|date:"F d, Y" }}</p>
                <p class="article-content">Diet for {{ order.days }} day/s</p>
                <p class="article-content">Price per day {{ order.diet_cost_per_day }} PLN</p>
                <p class="article-content">Last delivery {{ order.date_of_end|date:"F d, Y" }}</p>
                <p class="article-content">Megabytes: {{ order.megabytes }}</p>
                <p class="article-content">Delivery costs: {{ order.delivery_cost }}</p>
                <p class="price">Price {{ order.to_pay }} PLN </p>
                <h2>DELIVERY</h2>
                <p class="price"> Main address: {{ order.address }} </p>
                <p class="price"> House number: {{ order.address_info }} </p>
                <p class="price"> {{ order.post_code }} {{ order.locality }} </p>

            </div>
        </article>



    {% endfor %}

{% endblock %}

Backend Projects/CateringSite/checkout/templates/checkout/diet_order.html
{% extends "catering/base.html" %}
{% load crispy_forms_filters %}

{% load static %}
{% block head %}
    <title>{{ title }}</title>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    <link
            href="https://fonts.googleapis.com/css?family=Roboto:400,500"
            rel="stylesheet"
    />

    <link rel="stylesheet" type="text/css" href="{% static "checkout/css/maps.css" %}"/>
    <script src="{% static "checkout/js/maps.js" %}"></script>

    <!-- Async script executes immediately and must be after any DOM elements used in callback. -->
    <script
            src="https://maps.googleapis.com/maps/api/js?key={{ api_key }}&callback=initAutocomplete&libraries=places&v=weekly"
            async
    ></script>



{% endblock %}

{% block content %}

    <form action="" enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="my-button">Add</button>

    </form>

{% endblock %}

Backend Projects/CateringSite/checkout/templates/checkout/dietorder_confirm_delete.html
{% extends "catering/base.html" %}
{% block head %}
    <title>{{ title}}</title>
{% endblock %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-botom mb-4">Delete Order</legend>
                <h2>Are you sure to delete this order? "{{ object.name }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn-outline-danger" type="submit"> Yes</button>
                <a class="btn-outline-secondary" href="{% url "cart" %}">Cancel</a>

            </div>
        </form>
    </div>
{% endblock content %}

Backend Projects/CateringSite/checkout/templates/checkout/orders_history.html
{% extends "catering/base.html" %}
{% block head %}
    <title>{{ title}}</title>
{% endblock %}
{% block content %}

    {% for checkout in checkouts %}
        <article class="media content-section">
            <div class="media-body">
                <h2><a class="article-title" href="{% url "orders_history_detail" checkout.customer checkout.pk %}">Your
                    order from {{ checkout.date_of_purchase|date:"F d, Y" }}</a></h2>
                <p class="article-content">Costs: {{ checkout.to_pay }}</p>
                <p class="price"> Payment option {{ checkout.payment_method }}


            </div>
        </article>
    {% endfor %}

    {% if not checkouts %}
        <h4>Your history is empty :( </h4>
    {% endif %}


{% endblock %}